---
# hosts could have been "remote" or "all" as well
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
   - name: Uninstall Firefox
     apt:
       name: firefox
       state: absent
       update_cache: true