---
# run locally here
- hosts: localhost
  connection: local
  roles:
    - users
    - chrome
    - chrome-RDC
    - libreoffice
    - shotcut
    - cron
    - printer
    - theme
    - power
    - desktop