---
# tasks file for desktop
- name: Set app shortcuts
  copy:
    src: 14.json
    dest: ~/.cinnamon/configs/grouped-window-list@cinnamon.org/
- name: Set menu properties
  copy:
    src: 12.json
    dest: ~/.cinnamon/configs/menu@cinnamon.org/
- name: Creates theme directory
  file:
    path: ~/.themes
    state: directory
- name: Unarchive theme Adapta-Nokto
  unarchive:
    src: https://cinnamon-spices.linuxmint.com/files/themes/Adapta.zip
    dest: ~/.themes
    remote_src: yes
- name: Configure Desktop
  dconf:
    key: "{{ item.value.path }}"
    value: "{{ item.value.name }}"
    state: present
  loop: "{{ lookup('dict', settings) }}"
