---
# tasks file for desktop
- name: Configure Desktop
  dconf:
    key: "{{ item.value.path }}"
    value: "{{ item.value.name }}"
    state: present
  loop: "{{ lookup('dict', settings) }}"
  become: yes
  become_user: edd
- name: Set app shortcuts
  copy:
    src: 14.json
    dest: /home/edd/.cinnamon/configs/grouped-window-list@cinnamon.org/
    owner: edd
    group: edd
  become: yes
  become_user: edd
- name: Set menu properties
  copy:
    src: 12.json
    dest: /home/edd/.cinnamon/configs/menu@cinnamon.org/
    owner: edd
    group: edd
  become: yes
  become_user: edd