---
# tasks file for desktop
- name: Find app dock shortcuts settings file
  find:
    path: ~/.cinnamon/configs/grouped-window-list@cinnamon.org/
    patterns: ".*json$"
    use_regex: True
  register: file_grouped
- name: Set app dock shortcuts
  copy:
    src: grouped-window-list.json
    dest: "{{ item.path }}"
  with_items: " {{ file_grouped.files }}"
- name: Find menu settings file
  find:
    path: ~/.cinnamon/configs/menu@cinnamon.org/
    patterns: ".*json$"
    use_regex: True
  register: file_menu
- name: Set menu properties
  copy:
    src: menu.json
    dest: "{{ item.path }}"
  with_items: " {{ file_menu.files }}"
- name: Set qt theme
  copy:
    src: qt5ct.conf
    dest: ~/.config/qt5ct/
- name: Hide welcome screen
  copy:
    src: mintwelcome.desktop
    dest: ~/.config/autostart/
- name: Disable Flatpak update
  copy:
    src: mintinstall-update-flatpak.desktop
    dest: ~/.config/autostart/
- name: Disable Mint update
  copy:
    src: mintupdate.desktop
    dest: ~/.config/autostart/
- name: Set ansible startup script
  copy:
    src: ansible.desktop
    dest: ~/.config/autostart/
- name: Creates applications directory
  file:
    path: "{ item }}"
    state: directory
  with_items:
    - ~/.local/
    - ~/.local/share/
    - ~/.local/share/applications/
- name: Copy new chrome shortcut, disabling password manager
  copy:
    src: google-chrome.desktop
    dest: ~/.local/share/applications/
  when: ansible_user_id == "invite"
- name: Configure Desktop
  dconf:
    key: "{{ item.value.path }}"
    value: "{{ item.value.name }}"
    state: present
  loop: "{{ lookup('dict', settings) }}"
