---
- name: Add LibreOffice Repository
  apt_repository:
    repo: ppa:libreoffice/ppa
    state: present
    codename: bionic
  become: yes
- name: Install latest LibreOffice
  apt:
    pkg: libreoffice
    state: latest
    update_cache: true
  become: yes
- name: Install latest LibreOffice elementary style
  apt:
    pkg: libreoffice-style-elementary
    state: latest
    update_cache: true
  become: yes