---
# tasks file for printer
---
- name: "cups - installation"
  apt: 
    name: cups 
    state: installed 
    update_cache: yes 
    cache_valid_time: 3600
  become: yes

#- name: "cups - md5 on local printers.conf"
#  local_action: stat 
#    path: {{ playbook_dir }}/roles/homie/files/printers.conf 
#    get_md5: yes
#  register: locst

- name: "cups - md5 on remote printers.conf"
  stat: 
    path: /etc/cups/printers.conf 
    get_checksum: true
    checksum_algorithm:md5
  register: remst
  become: yes

- name: "cups - stop service"
  service: 
    name: cups
    state: stopped
  when: not remst.stat.exists or (md5_printerfile != remst.stat.md5)
  become: yes

- name: "cups - configure drivers"
  copy: 
    src: Ricoh-MP-2553.ppd
    dest: /etc/cups/ppd/Ricoh-MP-2553.ppd 
    mode: 0640 
    owner: root
    group: lp
    backup: yes 
  become: yes

- name: "cups - configure printers"
  copy: 
    src: printers.conf
    dest: /etc/cups/printers.conf
    mode: 600
    owner: root
    group: lp
    backup: yes
  notify: restart cups
  when: not remst.stat.exists or (md5_printerfile != remst.stat.md5)
  become: yes