---
# tasks file for users
- name: Protect admin user folder
  file:
    path: /home/edd
    owner: edd
    group: edd
    mode: '700'
    recurse: yes
  become: yes
  become_user: edd
- name: Add the invite user
  user:
    name: invite
    state: present
    password: "{{ invitePwd }}"
  become: yes
#- name: Set autologin user
#  copy:
#    src: lightdm.conf
#    dest: /etc/lightdm/
#    owner: root
#    group: root
#  become: yes