---
# tasks file for users
- file:
    path: /home/edd
    owner: edd
    group: edd
    mode: '700'
    recurse: yes
  become: yes
  become_user: edd
- name: Add the invite user
  user:
    name: invite
    state: present
    password: "{{ invitePwd }}"
  become: yes
