---
- name: Add Chrome Repository
  copy:
    src: google-chrome.list
    dest: /etc/apt/sources.list.d/
    owner: root
    group: root
  become: yes
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes
- name: Install Google chrome
  apt:
    pkg: google-chrome-stable
    state: present
    update_cache: true
  become: yes
- name: Creates policy directory
  file:
    path: "{{ item }}"
    state: directory
  become: yes
  with_items:
    - /etc/opt/
    - /etc/opt/chrome/
    - /etc/opt/chrome/policies/
    - /etc/opt/chrome/policies/managed/
- name: Set Chrome policies
  copy:
    src: edd-policy.json
    dest: /etc/opt/chrome/policies/managed/
    owner: root
    group: root
  become: yes
- name: Uninstall Firefox
  apt:
    pkg: firefox
    state: absent
  become: yes
