---
- name: Add Chrome Repository
  copy:
    src: google-chrome.list
    dest: /etc/apt/sources.list.d/
    owner: root
    group: root
  become: yes
- name: Add Chrome Apt signing key from URL
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes
- name: Install Google chrome
  apt:
    pkg: google-chrome-stable
    state: latest
    update_cache: true
  become: yes
- name: Creates Chrome policy directory
  file:
    path: "{{ item }}"
    state: directory
  become: yes
  with_items:
    - /etc/opt/
    - /etc/opt/chrome/
    - /etc/opt/chrome/policies/
    - /etc/opt/chrome/policies/managed/
- name: Set Chrome invite user policies
  copy:
    src: invite-policy.json
    dest: /etc/opt/chrome/policies/managed/
    owner: invite
    group: invite
    mode: 0400
  become: yes
- name: Set Chrome edd user policies
  copy:
    src: edd-policy.json
    dest: /etc/opt/chrome/policies/managed/
    owner: edd
    group: edd
    mode: 0400
  become: yes
- name: Uninstall Firefox browser
  apt:
    pkg: firefox
    state: absent
  become: yes
- name: Install Chrome Remote Desktop package
  apt:
    deb: https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
  become: yes
